categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🛠️ Chores'
    label: 'chore'
template: |
  ## What's Changed
  
  $CHANGES
